version: '3.8'
services:
  fullstack:
    build:
      context: ./
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - global-proxy-network

networks:
  global-proxy-network:
    external: true
